---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Create SSL certs folder
  file:
    path: "{{ kibana_cert_path }}"
    force: yes
    state: directory
    owner: kibana
    group: kibana
    mode: 0744
  when: kibana_ssl_access and kibana_ssl_certificate and kibana_ssl_key

- name: Copy ssl certificates for HTTPS.
  copy:
    src: "{{ item.file }}"
    dest: "{{ kibana_cert_path }}{{ item.destination }}"
    owner: kibana
    group: kibana
    mode: 0744
  loop:
    - {file: "{{kibana_ssl_certificate}}", destination: 'ssl.crt'}
    - {file: "{{kibana_ssl_key}}", destination: 'ssl.key'}
  when: kibana_ssl_access and kibana_ssl_certificate and kibana_ssl_key
  notify: restart kibana
